### ISSUE TITLE
new error

### ISSUE THREAD

**Issue by Karigar4039** [matrix/backports-rtl8187#10]
CC [M] /root/backports-rtl8187/tmp/backports/net/wireless/util.o
In file included from /root/backports-rtl8187/tmp/backports/net/wireless/util.c:15:
/root/backports-rtl8187/tmp/backports/include/net/cfg80211.h: In function ‘wdev_address’:
/root/backports-rtl8187/tmp/backports/include/net/cfg80211.h:5328:36: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
5328 | return wdev->netdev->dev_addr;
| ~~~~~~~~~~~~^~~~~~~~~~
/root/backports-rtl8187/tmp/backports/net/wireless/util.c: In function ‘cfg80211_send_layer2_update’:
/root/backports-rtl8187/tmp/backports/net/wireless/util.c:2121:9: error: implicit declaration of function ‘netif_rx_ni’; did you mean ‘netif_rx’? [-Werror=implicit-function-declaration]
2121 | netif_rx_ni(skb);
| ^~~~~~~~~~~
| netif_rx
cc1: some warnings being treated as errors
make[6]: *** [/usr/src/linux-headers-5.19.0-kali2-common/scripts/Makefile.build:254: /root/backports-rtl8187/tmp/backports/net/wireless/util.o] Error 1
make[5]: *** [/usr/src/linux-headers-5.19.0-kali2-common/scripts/Makefile.build:471: /root/backports-rtl8187/tmp/backports/net/wireless] Error 2
make[4]: *** [/usr/src/linux-headers-5.19.0-kali2-common/Makefile:1870: /root/backports-rtl8187/tmp/backports] Error 2
make[3]: *** [Makefile.build:13: modules] Error 2
make[2]: *** [Makefile.real:88: modules] Error 2
make[1]: *** [Makefile:43: modules] Error 2
make: *** [Makefile:30: default] Error 2
! Failed to build rtl8187 wireless driver.

Hello! by the way great effort.

but I am having difficulties. I have the following system details. host: Mac M1, guest: Kali Linux

Linux kali 5.19.0-kali2-arm64 https://github.com/matrix/backports-rtl8187/issues/1 SMP Debian 5.19.11-1kali2 (2022-10-10) aarch64 GNU/Linux

**Comment by matrix** [comment]
fixed with last commit
