### ISSUE TITLE
This script must not run as root

### ISSUE THREAD

**Issue by Shiro995** [matrix/backports-rtl8187#2]
Just as the title says, It gives me error this script must not run as root when trying to install it.
![image](https://user-images.githubusercontent.com/72838778/95925944-57527800-0dbb-11eb-81b8-77f6e870c4cf.png)

**Comment by matrix** [comment]
@Shiro995 you run as root. If you want, you can also comment out this line:

https://github.com/matrix/backports-rtl8187/blob/master/build.sh#L15
