### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by simontg** [matrix/backports-rtl8187#6]
Hi,
I'm trying install your driver to WSL2 machine ( Ububntu) 

when i run script ( build.h) i get some errors:

`Hunk #1 succeeded at 248 (offset -3 lines).
Generating local configuration database from kernel ...mkdir: cannot create directory ‘.tmp_11259’: Permission denied
mkdir: cannot create directory ‘.tmp_11261’: Permission denied
mkdir: cannot create directory ‘.tmp_11263’: Permission denied
mkdir: cannot create directory ‘.tmp_11265’: Permission denied
mkdir: cannot create directory ‘.tmp_11267’: Permission denied
mkdir: cannot create directory ‘.tmp_11269’: Permission denied
mkdir: cannot create directory ‘.tmp_11272’: Permission denied
mkdir: cannot create directory ‘.tmp_11274’: Permission denied
mkdir: cannot create directory ‘.tmp_11276’: Permission denied
mkdir: cannot create directory ‘.tmp_11278’: Permission denied
mkdir: cannot create directory ‘.tmp_11280’: Permission denied
mkdir: cannot create directory ‘.tmp_11282’: Permission denied
mkdir: cannot create directory ‘.tmp_11284’: Permission denied
mkdir: cannot create directory ‘.tmp_11286’: Permission denied
mkdir: cannot create directory ‘.tmp_11288’: Permission denied
mkdir: cannot create directory ‘.tmp_11290’: Permission denied
mkdir: cannot create directory ‘.tmp_11292’: Permission denied
mkdir: cannot create directory ‘.tmp_11294’: Permission denied
mkdir: cannot create directory ‘.tmp_11296’: Permission denied
mkdir: cannot create directory ‘.tmp_11298’: Permission denied
mkdir: cannot create directory ‘.tmp_11300’: Permission denied
mkdir: cannot create directory ‘.tmp_11302’: Permission denied
mkdir: cannot create directory ‘.tmp_11304’: Permission denied
mkdir: cannot create directory ‘.tmp_11306’: Permission denied
mkdir: cannot create directory ‘.tmp_11308’: Permission denied
mkdir: cannot create directory ‘.tmp_11310’: Permission denied
mkdir: cannot create directory ‘.tmp_11312’: Permission denied
mkdir: cannot create directory ‘.tmp_11314’: Permission denied
mkdir: cannot create directory ‘.tmp_11317’: Permission denied
mkdir: cannot create directory ‘.tmp_11319’: Permission denied
mkdir: cannot create directory ‘.tmp_11321’: Permission denied
mkdir: cannot create directory ‘.tmp_11323’: Permission denied
mkdir: cannot create directory ‘.tmp_11325’: Permission denied
mkdir: cannot create directory ‘.tmp_11327’: Permission denied
mkdir: cannot create directory ‘.tmp_11329’: Permission denied
mkdir: cannot create directory ‘.tmp_11331’: Permission denied
mkdir: cannot create directory ‘.tmp_11333’: Permission denied
mkdir: cannot create directory ‘.tmp_11335’: Permission denied
mkdir: cannot create directory ‘.tmp_11337’: Permission denied
 done.`
...
`/home/olek/backports/backports-rtl8187/tmp/backports/net/wireless/core.c:1134:2: error: implicit declaration of function ‘kzfree’; did you mean ‘kvfree’? [-Werror=implicit-function-declaration]
 1134 |  kzfree(wdev->wext.keys);
      |  ^~~~~~
      |  kvfree`
...
`Building backport-include/backport/autoconf.h ... done.
  CC [M]  /home/olek/backports/backports-rtl8187/tmp/backports/compat/main.o
  LD [M]  /home/olek/backports/backports-rtl8187/tmp/backports/compat/compat.o
  CC [M]  /home/olek/backports/backports-rtl8187/tmp/backports/drivers/net/wireless/realtek/rtl818x/rtl8187/dev.o
  CC [M]  /home/olek/backports/backports-rtl8187/tmp/backports/drivers/net/wireless/realtek/rtl818x/rtl8187/rtl8225.o
  CC [M]  /home/olek/backports/backports-rtl8187/tmp/backports/drivers/net/wireless/realtek/rtl818x/rtl8187/leds.o
  CC [M]  /home/olek/backports/backports-rtl8187/tmp/backports/drivers/net/wireless/realtek/rtl818x/rtl8187/rfkill.o
  LD [M]  /home/olek/backports/backports-rtl8187/tmp/backports/drivers/net/wireless/realtek/rtl818x/rtl8187/rtl8187.o
  CC [M]  /home/olek/backports/backports-rtl8187/tmp/backports/net/wireless/core.o
/home/olek/backports/backports-rtl8187/tmp/backports/net/wireless/core.c: In function ‘__cfg80211_unregister_wdev’:
/home/olek/backports/backports-rtl8187/tmp/backports/net/wireless/core.c:1134:2: error: implicit declaration of function ‘kzfree’; did you mean ‘kvfree’? [-Werror=implicit-function-declaration]
 1134 |  kzfree(wdev->wext.keys);
      |  ^~~~~~
      |  kvfree
cc1: some warnings being treated as errors
make[6]: *** [scripts/Makefile.build:279: /home/olek/backports/backports-rtl8187/tmp/backports/net/wireless/core.o] Error 1
make[5]: *** [scripts/Makefile.build:496: /home/olek/backports/backports-rtl8187/tmp/backports/net/wireless] Error 2
make[4]: *** [Makefile:1801: /home/olek/backports/backports-rtl8187/tmp/backports] Error 2
make[3]: *** [Makefile.build:13: modules] Error 2
make[2]: *** [Makefile.real:88: modules] Error 2
make[1]: *** [Makefile:43: modules] Error 2
make: *** [Makefile:30: default] Error 2
! Failed to build rtl8187 wireless driver.`

can you help me witch this ?

**Comment by simontg** [comment]
when I comment couple first lines ( I put #) , 
then I have problem with this:

`Building backport-include/backport/autoconf.h ... done.
  CC [M]  /home/olek/backports2/backports-rtl8187/tmp/backports/compat/main.o
  LD [M]  /home/olek/backports2/backports-rtl8187/tmp/backports/compat/compat.o
  CC [M]  /home/olek/backports2/backports-rtl8187/tmp/backports/drivers/net/wireless/realtek/rtl818x/rtl8187/dev.o
  CC [M]  /home/olek/backports2/backports-rtl8187/tmp/backports/drivers/net/wireless/realtek/rtl818x/rtl8187/rtl8225.o
  CC [M]  /home/olek/backports2/backports-rtl8187/tmp/backports/drivers/net/wireless/realtek/rtl818x/rtl8187/leds.o
  CC [M]  /home/olek/backports2/backports-rtl8187/tmp/backports/drivers/net/wireless/realtek/rtl818x/rtl8187/rfkill.o
  LD [M]  /home/olek/backports2/backports-rtl8187/tmp/backports/drivers/net/wireless/realtek/rtl818x/rtl8187/rtl8187.o
  CC [M]  /home/olek/backports2/backports-rtl8187/tmp/backports/net/wireless/core.o
/home/olek/backports2/backports-rtl8187/tmp/backports/net/wireless/core.c: In function ‘__cfg80211_unregister_wdev’:
/home/olek/backports2/backports-rtl8187/tmp/backports/net/wireless/core.c:1134:2: error: implicit declaration of function ‘kzfree’; did you mean ‘kvfree’? [-Werror=implicit-function-declaration]
 1134 |  kzfree(wdev->wext.keys);
      |  ^~~~~~
      |  kvfree
cc1: some warnings being treated as errors
make[6]: *** [scripts/Makefile.build:279: /home/olek/backports2/backports-rtl8187/tmp/backports/net/wireless/core.o] Error 1
make[5]: *** [scripts/Makefile.build:496: /home/olek/backports2/backports-rtl8187/tmp/backports/net/wireless] Error 2
make[4]: *** [Makefile:1801: /home/olek/backports2/backports-rtl8187/tmp/backports] Error 2
make[3]: *** [Makefile.build:13: modules] Error 2
make[2]: *** [Makefile.real:88: modules] Error 2
make[1]: *** [Makefile:43: modules] Error 2
make: *** [Makefile:30: default] Error 2
! Failed to build rtl8187 wireless driver.`

**Comment by matrix** [comment]
Hi, I can't reproduce locally ... please retry with latest version and eventually reopen the issue. Thanks
