### ISSUE TITLE
Can't install...

### ISSUE THREAD

**Issue by chichke** [matrix/backports-rtl8187#7]
<img width="408" alt="Capture d’écran 2021-07-08 à 6 03 54 PM" src="https://user-images.githubusercontent.com/26006762/124954960-ed4bc400-e016-11eb-94f8-dd6f5f096302.png">

**Comment by matrix** [comment]
Please read the error message before open an issue. "lex: No such file or directory".
Thanks

**Comment by chichke** [comment]
Sorry but what should I do?

**Comment by matrix** [comment]
install flex

**Comment by chichke** [comment]
`sudo apt install flex bison` fixed it on ParrotOS

**Comment by chichke** [comment]
<img width="409" alt="Capture d’écran 2021-07-08 à 6 18 30 PM" src="https://user-images.githubusercontent.com/26006762/124957012-e756e280-e018-11eb-861b-d7cd035914af.png">

Permission error while `./build.sh -i`

**Comment by matrix** [comment]
please pull now and retry
